component_depth: 1
languages:
- objectivec
exclude:
- ./antlr-ant/.*
- ./antlr-ant/main/.*
- ./antlr-ant/main/antlr3-task/.*
- ./antlr3-maven-archetype/.*
- ./antlr3-maven-plugin/.*
- ./bin/.*
- ./bin/org/.*
- ./bin/org/antlr/.*
- ./bin/org/antlr/analysis/.*
- ./bin/org/antlr/codegen/.*
- ./bin/org/antlr/gunit/.*
- ./bin/org/antlr/gunit/swingui/.*
- ./bin/org/antlr/gunit/swingui/model/.*
- ./bin/org/antlr/gunit/swingui/runner/.*
- ./bin/org/antlr/misc/.*
- ./bin/org/antlr/mojo/.*
- ./bin/org/antlr/mojo/antlr3/.*
- ./bin/org/antlr/runtime/.*
- ./bin/org/antlr/runtime/debug/.*
- ./bin/org/antlr/runtime/misc/.*
- ./bin/org/antlr/runtime/tree/.*
- ./bin/org/antlr/test/.*
- ./bin/org/antlr/tool/.*
- ./bin/org/apache/.*
- ./bin/org/apache/tools/.*
- ./bin/org/apache/tools/ant/.*
- ./bin/org/apache/tools/ant/antlr/.*
- ./gunit/.*
- ./gunit-maven-plugin/.*
- ./lib/.*
- ./runtime/.*
- ./runtime/ActionScript/.*
- ./runtime/ActionScript/lib/.*
- ./runtime/ActionScript/project/.*
- ./runtime/ActionScript/project/lib/.*
- ./runtime/ActionScript/project/test/.*
- ./runtime/ActionScript/project/test/org/.*
- ./runtime/ActionScript/project/test/org/antlr/.*
- ./runtime/ActionScript/project/test/org/antlr/runtime/.*
- ./runtime/ActionScript/project/test/org/antlr/runtime/test/.*
- ./runtime/C/.*
- ./runtime/C/dist/.*
- ./runtime/C/doxygen/.*
- ./runtime/C/include/.*
- ./runtime/C/m4/.*
- ./runtime/C/vsrulefiles/.*
- ./runtime/CSharp2/.*
- ./runtime/CSharp2/Libraries/.*
- ./runtime/CSharp2/Libraries/MbUnit/.*
- ./runtime/CSharp2/Libraries/StringTemplate.NET/.*
- ./runtime/CSharp2/Libraries/StringTemplate.NET/net-2.0/.*
- ./runtime/CSharp2/dist/.*
- ./runtime/CSharp3/.*
- ./runtime/Delphi/.*
- ./runtime/Java/.*
- ./runtime/JavaScript/.*
- ./runtime/JavaScript/build/.*
- ./runtime/JavaScript/tests/.*
- ./runtime/JavaScript/tests/functional/.*
- ./runtime/JavaScript/third/.*
- ./runtime/ObjC/.*
- ./runtime/ObjC/ANTLR.framework/.*
- ./runtime/ObjC/ANTLR.framework/Headers/.*
- ./runtime/ObjC/ANTLR.framework/Versions/.*
- ./runtime/ObjC/ANTLR.framework/Versions/A/.*
- ./runtime/ObjC/ANTLR.framework/Versions/A/Headers/.*
- ./runtime/ObjC/ANTLR.framework/Versions/Current/.*
- ./runtime/ObjC/ANTLR.framework/Versions/Current/Headers/.*
- ./runtime/ObjC/Framework/.*
- ./runtime/ObjC/Framework/ANTLR/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR/en.lproj/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/project.xcworkspace/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/project.xcworkspace/xcuserdata/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/project.xcworkspace/xcuserdata/acondit.xcuserdatad/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/project.xcworkspace/xcuserdata/acondit.xcuserdatad/xcdebugger/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/xcuserdata/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/xcuserdata/acondit.xcuserdatad/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/xcuserdata/acondit.xcuserdatad/xcdebugger/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLR.xcodeproj/xcuserdata/acondit.xcuserdatad/xcschemes/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLRTests/.*
- ./runtime/ObjC/Framework/ANTLR/ANTLRTests/en.lproj/.*
- ./runtime/ObjC/Framework/ANTLR.xcodeproj/.*
- ./runtime/ObjC/Framework/English.lproj/.*
- ./runtime/ObjC/Framework/build/.*
- ./runtime/ObjC/Framework/build/ANTLR.build/.*
- ./runtime/ObjC/Framework/build/ANTLR.build/Debug/.*
- ./runtime/ObjC/Framework/build/ANTLR.build/Debug/ANTLR.build/.*
- ./runtime/ObjC/Framework/build/ANTLR.build/Debug/ANTLR.build/Objects-normal/.*
- ./runtime/ObjC/Framework/build/ANTLR.build/Debug/ANTLR.build/Objects-normal/i386/.*
- ./runtime/ObjC/Framework/examples/.*
- ./runtime/ObjC/Framework/examples/LL-star/.*
- ./runtime/ObjC/Framework/examples/combined/.*
- ./runtime/ObjC/Framework/examples/combined/output1/.*
- ./runtime/ObjC/Framework/examples/fuzzy/.*
- ./runtime/ObjC/Framework/examples/fuzzy/output1/.*
- ./runtime/ObjC/Framework/examples/hoistedPredicates/.*
- ./runtime/ObjC/Framework/examples/lexertest-simple/.*
- ./runtime/ObjC/Framework/examples/lexertest-simple/output1/.*
- ./runtime/ObjC/Framework/examples/scopes/.*
- ./runtime/ObjC/Framework/examples/scopes/output1/.*
- ./runtime/ObjC/Framework/examples/simplecTreeParser/.*
- ./runtime/ObjC/Framework/examples/simplecTreeParser/output1/.*
- ./runtime/ObjC/Framework/examples/treeparser/.*
- ./runtime/ObjC/Framework/examples/treerewrite/.*
- ./runtime/ObjC/Framework/examples/treerewrite/output1/.*
- ./runtime/ObjC/Framework/test/.*
- ./runtime/ObjC/Framework/test/runtime/.*
- ./runtime/ObjC/Framework/test/runtime/TestRewriteRuleTokenStream/.*
- ./runtime/ObjC/Framework/test/runtime/misc/.*
- ./runtime/ObjC/Framework/test/runtime/recognizer/.*
- ./runtime/ObjC/Framework/test/runtime/sets/.*
- ./runtime/ObjC/Framework/test/runtime/stream/.*
- ./runtime/ObjC/Framework/test/runtime/token/.*
- ./runtime/ObjC/Framework/test/runtime/tree/.*
- ./runtime/Perl5/.*
- ./runtime/Perl5/docs/.*
- ./runtime/Perl5/examples/.*
- ./runtime/Perl5/examples/expr/.*
- ./runtime/Perl5/examples/id/.*
- ./runtime/Perl5/examples/mexpr/.*
- ./runtime/Perl5/examples/simplecalc/.*
- ./runtime/Perl5/examples/tweak/.*
- ./runtime/Perl5/examples/zero-one/.*
- ./runtime/Perl5/lib/.*
- ./runtime/Perl5/lib/ANTLR/.*
- ./runtime/Perl5/lib/ANTLR/Runtime/.*
- ./runtime/Perl5/t/.*
- ./runtime/Perl5/t/author/.*
- ./runtime/Perl5/t/classes/.*
- ./runtime/Perl5/t/classes/Test/.*
- ./runtime/Perl5/t/classes/Test/ANTLR/.*
- ./runtime/Perl5/t/classes/Test/ANTLR/Runtime/.*
- ./runtime/Perl5/t/examples/.*
- ./runtime/Perl5/t/lib/.*
- ./runtime/Perl5/t/lib/ANTLR/.*
- ./runtime/Perl5/t/lib/ANTLR/Runtime/.*
- ./runtime/Perl5/t/lib/My/.*
- ./runtime/Perl5/t/lib/My/Test/.*
- ./runtime/Perl5/t/lib/My/Test/Class/.*
- ./runtime/Perl5/tools/.*
- ./runtime/Python/.*
- ./runtime/Python/antlr3/.*
- ./runtime/Python/dist/.*
- ./runtime/Python/tests/.*
- ./runtime/Python/unittests/.*
- ./runtime/Ruby/.*
- ./runtime/Ruby/lib/.*
- ./runtime/Ruby/lib/antlr3/.*
- ./runtime/Ruby/lib/antlr3/debug/.*
- ./runtime/Ruby/lib/antlr3/modes/.*
- ./runtime/Ruby/lib/antlr3/streams/.*
- ./runtime/Ruby/lib/antlr3/template/.*
- ./runtime/Ruby/lib/antlr3/test/.*
- ./runtime/Ruby/lib/antlr3/tree/.*
- ./runtime/Ruby/test/.*
- ./runtime/Ruby/test/functional/.*
- ./runtime/Ruby/test/functional/ast-output/.*
- ./runtime/Ruby/test/functional/debugging/.*
- ./runtime/Ruby/test/functional/delegation/.*
- ./runtime/Ruby/test/functional/lexer/.*
- ./runtime/Ruby/test/functional/main/.*
- ./runtime/Ruby/test/functional/parser/.*
- ./runtime/Ruby/test/functional/template-output/.*
- ./runtime/Ruby/test/functional/token-rewrite/.*
- ./runtime/Ruby/test/functional/tree-parser/.*
- ./runtime/Ruby/test/unit/.*
- ./runtime/Ruby/test/unit/sample-input/.*
- ./tool/.*
